[project]
name = "chart-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastmcp>=2.14.5",
    "google-generativeai>=0.8.6",
    "matplotlib>=3.10.8",
]
